---
- name: "ALARM | Configure IPv6 IPTables"
  hosts:
  sudo: false
  gather_facts: false
  tasks:
    - name: "ALARM | IP6Tables | Check if IPT6ables Save File exists"
      stat: path=/etc/iptables/ip6tables.rules
      register: ip6tables

    - name: "ALARM | IP6Tables | Create IP6Tables save file if it does not exist"
      file: path=/etc/iptables/ip6tables.rules state=touch mode=0744
      when: ip6tables.stat.exists == False

    - name: "ALARM | IP6Tables | Flush the rules if the save file exists"
      command: ip6tables -f
      when: ip6tables.stat.exists == True

    - name: "ALARM | IP6Tables | Enable IP6Tables"
      service: name=ip6tables enabled=yes state=started

    - name: "ALARM | IP6Tables | Enable loopback traffic through the firewall"
      command: ip6tables -I INPUT 1 -i lo -j ACCEPT

    - name: "ALARM | IP6Tables | Enable SSH traffic through the firewall"
      command: ip6tables -A INPUT -p tcp --dport ssh -j ACCEPT

    - name: "ALARM | IP6Tables | Enable outbound connections to receive incoming traffic back"
      command: "ip6tables -I INPUT -m state --state ESTABLISHED,RELATED -j ACCEPT"

    - name: "ALARM | IP6Tables | Enable outbound DNS"
      command: "ip6tables -A OUTPUT -p udp -o eth0 --dport 53 -j ACCEPT && ip6tables -A INPUT -p udp -i eth0 --sport 53 -j ACCEPT"

    - name: "ALARM | IP6Tables | Enable outbound PING"
      command: "ip6tables -A OUTPUT -p icmp --icmp-type echo-request -j ACCEPT && ip6tables -A INPUT -p icmp --icmp-type echo-reply -j ACCEPT"

    - name: "ALARM | IP6Tables | Enable Docker containers to access online repositories"
      command: "ip6tables -A FORWARD -i docker0 -o eth0 -j ACCEPT && ip6tables -A FORWARD -i eth0 -o docker0 -j ACCEPT"

    - name: "ALARM | IP6Tables | LAST RULE! Drop any traffic not matching our pre-set rules"
      command: ip6tables -A INPUT -j DROP

    - name: "ALARM | IP6Tables | Save the firewall rules"
      command: ip6tables-save > /etc/iptables/ip6tables.rules

    - name: "ALARM | IP6Tables | Check if ip6tables.service.d directory already exists"
      stat: path=/etc/systemd/system/ipt6ables.service.d
      register: ip6tablesservice

    - name: "ALARM | IP6Tables | Create the directory for ip6tables fix if it does not exist"
      file: path=/etc/systemd/system/ip6tables.service.d state=directory mode=0755
      when: ip6tablesservice.stat.exists == False

    - name: "ALARM | IP6Tables | Check if the configuration file already exists"
      stat: path=/etc/systemd/system/ip6tables.service.d/00-pre-network.conf
      register: prenetworkconf6

    - name: "ALARM | IP6Tables | Create the configuration file if it does not exist"
      file: path=/etc/systemd/system/ip6tables.service.d/00-pre-network.conf state=touch mode=0755
      when: prenetworkconf6.stat.exists == False

    - name: "ALARM | IP6Tables | Populate the configuration file (required by 1.4.21-1 package as it is out of date)"
      command: >
        cat /etc/systemd/system/ip6tables.service.d/00-pre-network.conf <<EOF
        [Unit]
        Wants=network-pre.target
        Before=network-pre.target
        EOF