---
# Do not sudo this task!
- name: "reboot"
  command: "shutdown -r +1"
  async: 1
  poll: 0
  ignore_errors: true

# Wait for reboot to complete
  # Timing specific to Raspberry Pi 2 Model B restart time with Class 10 MicroSD card
- name: "wait"
  local_action: "wait_for port=22 host={{ ansible_ssh_host }} search_regex=OpenSSH delay=65"
  when: ansible_architecture == "armv7l"